translate mode added

diff --git a/whisper-stream b/whisper-stream
--- a/whisper-stream
+++ b/whisper-stream
@@ -1,20 +1,23 @@
 #!/bin/bash
 
-VERSION="1.0.7"
+# Default configuration and versioning
+VERSION="1.0.8"
 
-# Set the default sensitivity values
-MIN_VOLUME=1%
-SILENCE_LENGTH=1.5
-ONESHOT=false
-DURATION=0
-TOKEN=""
-OUTPUT_DIR=""
-PROMPT=""
-LANGUAGE=""
-AUDIO_FILE=""
-PIPE_TO_CMD=""
+# Setting the default values for the script parameters
+MIN_VOLUME=1%                  # Minimum volume threshold
+SILENCE_LENGTH=1.5             # Minimum silence duration in seconds
+ONESHOT=false                  # Flag to determine if the script should run once or continuously
+DURATION=0                     # Duration of the recording in seconds (0 means continuous)
+MODEL="whisper-1"              # Model for the OpenAI API
+TOKEN=""                       # OpenAI API token
+OUTPUT_DIR=""                  # Directory to save the transcriptions
+PROMPT=""                      # Prompt for the API call
+LANGUAGE=""                    # Language code for transcription
+TRANSLATE=""                   # Flag to indicate translation to English
+AUDIO_FILE=""                  # Specific audio file for transcription
+PIPE_TO_CMD=""                 # Command to pipe the transcribed text to
 
-# Function to display the help message
+# Display help information for script usage
 function display_help() {
   echo "Usage: $0 [options]"
   echo "Options:"
@@ -27,6 +30,7 @@ function display_help() {
   echo "  -r, --prompt <value>     Set the prompt for the API call"
   echo "  -l, --language <value>   Set the language in ISO-639-1 format"
   echo "  -f, --file <value>       Set the audio file to be transcribed"
+  echo "  -tr, --translate         Translate the transcribed text to English"
   echo "  -p2, --pipe-to <cmd>     Pipe the transcribed text to the specified command (e.g., 'wc -m')"
   echo "  -V, --version            Show the version number"
   echo "  -h, --help               Display this help message"
@@ -34,7 +38,7 @@ function display_help() {
   exit 0
 }
 
-# Function to check if the audio file is valid
+# Check the validity of the provided audio file
 function check_audio_file() {
   local file=$1
 
@@ -77,7 +81,7 @@ function check_audio_file() {
   esac
 }
 
-# Parse command-line arguments
+# Parse command-line arguments to set script parameters
 while [[ $# -gt 0 ]]; do
   key="$1"
   case $key in
@@ -87,6 +91,9 @@ while [[ $# -gt 0 ]]; do
         exit 1
       fi
       MIN_VOLUME="$2"
+      if [[ "$MIN_VOLUME" != *% ]]; then
+        MIN_VOLUME+="%"
+      fi
       shift
       shift
       ;;
@@ -127,6 +134,11 @@ while [[ $# -gt 0 ]]; do
         exit 1
       fi
       OUTPUT_DIR="$2"
+      # check if the output directory exists
+      if [ ! -d "$OUTPUT_DIR" ]; then
+        echo "Directory does not exist: $OUTPUT_DIR"
+        exit 1
+      fi
       shift
       shift
       ;;
@@ -146,6 +158,10 @@ while [[ $# -gt 0 ]]; do
       fi
       LANGUAGE="$2"
       shift
+      shift
+      ;;
+    -tr|--translate)
+      TRANSLATE=true
       shift
       ;;
     -p2|--pipe-to)
@@ -181,13 +197,13 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-# If the version option is specified, display the version number and exit
+# Display version if the version flag is set
 if [ "$SHOW_VERSION" = true ]; then
-  echo "Whisper Stream Voice-to-Text Transcriber (version: $VERSION)"
+  echo "Whisper Stream Speech-to-Text Transcriber (version: $VERSION)"
   exit
 fi
 
-# If no token is provided as an argument, try to get it from the environment variable
+# Fetch OpenAI API token from environment if not provided as an argument
 if [ -z "$TOKEN" ]; then
   TOKEN="${OPENAI_API_KEY:-}"
 fi
@@ -198,20 +214,8 @@ if [ -z "$TOKEN" ]; then
   exit 1
 fi
 
-# Set the model for audio transcription
-MODEL="whisper-1"
 
-# Set the maximum number of retries
-MAX_RETRIES=3
-
-# Set the timeout duration in seconds
-TIMEOUT_SECONDS=5
-
-# Array to store the output file names
-output_files=()
-
-# Variable to store the accumulated text
-accumulated_text=""
+output_files=() # Array to store the names of output audio files
 
 # Function to get the name of the current audio input device on macOS
 function get_macos_input_device() {
@@ -251,17 +255,21 @@ function get_linux_input_volume() {
 # Function to display current settings
 function display_settings() {
   echo ""
-  echo $'\e[1;34m'Whisper Stream Transcriber$'\e[0m' ${VERSION}
-  echo $'\e[1;33m'---------------------------------------------$'\e[0m'
+  echo $'\e[1;34m'Whisper Stream Speech-to-Text Transcriber$'\e[0m' ${VERSION}
+  echo $'\e[1;33m'-----------------------------------------------$'\e[0m'
   echo "Current settings:"
   echo "  Volume threshold: $MIN_VOLUME"
   echo "  Silence length: $SILENCE_LENGTH seconds"
   echo "  Input language: ${LANGUAGE:-Not specified}"
 
+  if [ -n "$TRANSLATE" ]; then
+    echo "  Translate to English: $TRANSLATE"
+  fi
+  
   if [ -n "$OUTPUT_DIR" ]; then
     echo "  Output Dir: $OUTPUT_DIR"
   fi
-  
+
   # Get the input device based on the operating system
   local input_device=$(get_input_device)
   if [ -n "$input_device" ]; then
@@ -274,12 +282,12 @@ function display_settings() {
     echo "  Input volume: $input_volume"
   fi
   
-  echo $'\e[1;33m'---------------------------------------------$'\e[0m'
+  echo $'\e[1;33m'-----------------------------------------------$'\e[0m'
   echo To stop the app, press $'\e[0;36m'Ctrl+C$'\e[0m'
   echo ""
 }
 
-# Function to get the name of the current audio input device based on the operating system
+# Get the name of the current audio input device based on OS
 function get_input_device() {
   case "$(uname)" in
     Darwin)
@@ -294,8 +302,7 @@ function get_input_device() {
   esac
 }
 
-
-# Function to get the volume of the current audio input device based on the operating system
+# Get the volume level of the current audio input device based on OS
 function get_input_volume() {
   case "$(uname)" in
     Darwin)
@@ -310,7 +317,7 @@ function get_input_volume() {
   esac
 }
 
-# Spinner
+# Display a rotating spinner animation
 function spinner() {
   local pid=$1
   local delay=0.1
@@ -321,13 +328,19 @@ function spinner() {
     local spinstr=$temp${spinstr%"$temp"}
     sleep $delay
   done
+  printf "\r\e[K"
 }
 
-# Function to convert audio to text using the Whisper API
+# Convert the audio to text using the OpenAI Whisper API
 function convert_audio_to_text() {
   local output_file=$1
+  if [ -n "$TRANSLATE" ]; then
+    base_url="https://api.openai.com/v1/audio/translations"
+  else
+    base_url="https://api.openai.com/v1/audio/transcriptions"
+  fi
   local curl_command="curl -s --request POST \
-    --url https://api.openai.com/v1/audio/transcriptions \
+    --url $base_url \
     --header \"Authorization: Bearer $TOKEN\" \
     --header \"Content-Type: multipart/form-data\" \
     --form \"file=@$output_file\" \
@@ -342,22 +355,30 @@ function convert_audio_to_text() {
     curl_command+=" --form \"language=$LANGUAGE\""
   fi
 
+  maxretries=3
+
   response=$(eval $curl_command)
   # Check if the curl command was successful
-  if [ $? -ne 0 ]; then
-    echo "API call failed."
-    return 1
-  fi
+  # retry until successful or max retries reached
+  while [ $? -ne 0 ] && [ $maxretries -gt 0 ]; do
+    # print a red dot to indicate a failed API call
+    printf "\e[1;31m.\e[0m"
+    response=$(eval $curl_command)
+    maxretries=$((maxretries - 1))
+  done
 
   transcription=$(echo "$response" | jq -r '.text')
   
-  # Check if the transcription was successful
-  if [ $? -ne 0 ]; then
-    echo "Failed to parse the response."
-    return 1
-  fi
+  # Check if the curl command was successful
+  # retry until successful or max retries reached
+  while [ $? -ne 0 ] && [ $maxretries -gt 0 ]; do
+    # print a red dot to indicate a failed API call
+    printf "\e[1;31m.\e[0m"
+    response=$(eval $curl_command)
+    maxretries=$((maxretries - 1))
+  done
 
-  echo -ne "\r"
+  printf "\r\e[K"
   echo "$transcription"
 
   if [ -n "$PIPE_TO_CMD" ]; then
@@ -370,15 +391,13 @@ function convert_audio_to_text() {
     rm -f "$output_file"
   fi
   
-  # Accumulate the transcribed text
+  # Accumulate the transcribed text in a temporary file
+  # this is necessary for the data to be available when the script terminates
   echo "$transcription" >> temp_transcriptions.txt
 }
 
-# Function to handle script termination
+# Handle the script termination: clean up and save transcriptions
 function handle_exit() {
-
- # Clear the current line
-  printf "\r\e[K\n"
 
   # Wait for all background jobs to finish
   wait
@@ -391,8 +410,18 @@ function handle_exit() {
     rm -f "$file"
   done
 
-  # Remove temp transcriptions file
-  rm -f temp_transcriptions.txt
+  # if temp_transcriptions.txt exists, remove it
+  if [ -f temp_transcriptions.txt ]; then
+    # read data from temp_transcriptions.txt into the accumulated_text variable
+    # and remove temp_transcriptions.txt
+    accumulated_text=$(cat temp_transcriptions.txt)
+    rm -f temp_transcriptions.txt
+    # Clear the current line
+    printf "\r\e[K\n"
+  else
+    printf "\r\e[K"
+    exit
+  fi
 
   # If output directory is specified, create a text file with the accumulated text in the specified directory
   if [ -n "$OUTPUT_DIR" ]; then
@@ -430,92 +459,38 @@ function handle_exit() {
   exit
 }
 
-# Function to retry API call
-function retry_api_call() {
-  local retries=0
-  local response=""
-  local output_file=$1
-  
-  while [ $retries -lt $MAX_RETRIES ]; do
-    echo "Attempt $((retries+1))..."
-    response=$(custom_timeout "$TIMEOUT_SECONDS" convert_audio_to_text "$output_file")
-    
-    if [ $? -eq 0 ]; then
-      echo "$response"
-      return 0
-    else
-      retries=$((retries + 1))
-      sleep 1
-    fi
-  done
-  
-  echo "API call failed after $MAX_RETRIES retries."
-  return 1
-}
-
-# Custom timeout function
-function custom_timeout() {
-  local timeout=$1
-  shift
-  
-  # Run the command in the background
-  "$@" &
-  local pid=$!
-  
-  # Wait for the command to finish or timeout
-  ( sleep "$timeout" && kill -9 "$pid" ) 2>/dev/null &
-  local watchdog=$!
-  
-  # Wait for the command or watchdog to finish
-  wait "$pid" 2>/dev/null
-  local result=$?
-  
-  # Clean up the watchdog process
-  kill -9 "$watchdog" 2>/dev/null
-  
-  return $result
-}
-
-
-# If an audio file is provided as an argument, convert it to text and exit
+# If an audio file is provided, convert it to text and then exit
 if [ -n "$AUDIO_FILE" ]; then
   echo ""
   echo $'\e[1;34m'Whisper Stream Transcriber$'\e[0m' ${VERSION}
-  echo $'\e[1;33m'---------------------------------------------$'\e[0m'
+  echo $'\e[1;33m'-----------------------------------------------$'\e[0m'
   echo "Current settings:"
   echo "  Input language: ${LANGUAGE:-Not specified}"
-  echo "  Input file: $AUDIO_FILE"
 
+  if [ -n "$TRANSLATE" ]; then
+    echo "  Translate to English: $TRANSLATE"
+  fi
+  
   if [ -n "$OUTPUT_DIR" ]; then
     echo "  Output Dir: $OUTPUT_DIR"
   fi
-  
-  echo $'\e[1;33m'---------------------------------------------$'\e[0m'
+
+  echo "  Input file: $AUDIO_FILE"
+  echo $'\e[1;33m'-----------------------------------------------$'\e[0m'
   echo $'\e[0;36m'Please wait ...$'\e[0m'
   echo ""
 
   convert_audio_to_text "$AUDIO_FILE"
-  # Read the transcriptions into the accumulated_text variable
-  while IFS= read -r line; do
-    if [ -z "$accumulated_text" ]; then
-      accumulated_text="$line"
-    else
-      accumulated_text+="
-      $line"
-    fi
-  done < temp_transcriptions.txt
-  # Clear the temporary transcriptions file
-  > temp_transcriptions.txt
   handle_exit
 fi
 
-# Call the functions to display current settings
+# Display the current configuration/settings of the script
 display_settings
 
-# Trap SIGINT (Ctrl+C), SIGTSTP (Ctrl+Z) and call handle_exit()
+# Handle script termination using trap for SIGINT (Ctrl+C) and SIGTSTP (Ctrl+Z)
 trap handle_exit SIGINT SIGTSTP
 
-# Start recording audio using SoX and detect silence
+# Main loop to continuously record audio, detect silence, and transcribe audio
 while true; do
   # Set the path to the output audio file
   OUTPUT_FILE="output_$(date +%s).mp3"
@@ -523,7 +498,8 @@ while true; do
   # Add the output file to the array
   output_files+=("$OUTPUT_FILE")
 
-  echo -n $'\e[1;32m'▶ $'\e[0m'
+  # Add a prompt at the beginning of the recording
+  # echo -n $'\e[1;32m'▶ $'\e[0m'
 
   # Record audio in raw format then convert to mp3
   if [ "$DURATION" -gt 0 ]; then
@@ -543,18 +519,8 @@ while true; do
 
     # Captures the process ID of the last executed background command.
     pid=$!
-    spinner $pid
+    spinner $pid &
     # Read the transcriptions into the accumulated_text variable
-    while IFS= read -r line; do
-      if [ -z "$accumulated_text" ]; then
-        accumulated_text="$line"
-      else
-        accumulated_text+="
-$line"
-      fi
-    done < temp_transcriptions.txt
-    # Clear the temporary transcriptions file
-    > temp_transcriptions.txt
   else
     echo "No audio recorded."
   fi
@@ -564,4 +530,5 @@ $line"
   fi
 done
 
+# Handle final cleanup and exit
 handle_exit
