added timestamp_gramularities option

diff --git a/whisper-stream b/whisper-stream
--- a/whisper-stream
+++ b/whisper-stream
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Default configuration and versioning
-VERSION="1.0.9"
+VERSION="1.1.0"
 
 # Setting the default values for the script parameters
 MIN_VOLUME=1%                  # Minimum volume threshold
@@ -17,25 +17,27 @@ TRANSLATE=""                   # Flag to indicate translation to English
 AUDIO_FILE=""                  # Specific audio file for transcription
 PIPE_TO_CMD=""                 # Command to pipe the transcribed text to
 QUIET_MODE=false               # Flag to determine if the banner and settings should be suppressed
+GRANULARITIES="none"           # Timestamp granularities for transcription: segment or word
 
 # Display help information for script usage
 function display_help() {
   echo "Usage: $0 [options]"
   echo "Options:"
-  echo "  -v, --volume <value>     Set the minimum volume threshold (default: 1%)"
-  echo "  -s, --silence <value>    Set the minimum silence length (default: 1.5)"
-  echo "  -o, --oneshot            Enable one-shot mode"
-  echo "  -d, --duration <value>   Set the recording duration in seconds (default: 0, continuous)"
-  echo "  -t, --token <value>      Set the OpenAI API token"
-  echo "  -p, --path <value>       Set the output directory path to create the transcription file"
-  echo "  -r, --prompt <value>     Set the prompt for the API call"
-  echo "  -l, --language <value>   Set the language in ISO-639-1 format"
-  echo "  -f, --file <value>       Set the audio file to be transcribed"
-  echo "  -tr, --translate         Translate the transcribed text to English"
-  echo "  -p2, --pipe-to <cmd>     Pipe the transcribed text to the specified command (e.g., 'wc -m')"
-  echo "  -V, --version            Show the version number"
-  echo "  -q, --quiet              Suppress the banner and settings"
-  echo "  -h, --help               Display this help message"
+  echo "  -v, --volume <value>        Set the minimum volume threshold (default: 1%)"
+  echo "  -s, --silence <value>       Set the minimum silence length (default: 1.5)"
+  echo "  -o, --oneshot               Enable one-shot mode"
+  echo "  -d, --duration <value>      Set the recording duration in seconds (default: 0, continuous)"
+  echo "  -t, --token <value>         Set the OpenAI API token"
+  echo "  -p, --path <value>          Set the output directory path to create the transcription file"
+  echo "  -g, --granularities <value> Set the timestamp granularities (segment or word)"
+  echo "  -r, --prompt <value>        Set the prompt for the API call"
+  echo "  -l, --language <value>      Set the language in ISO-639-1 format"
+  echo "  -f, --file <value>          Set the audio file to be transcribed"
+  echo "  -tr, --translate            Translate the transcribed text to English"
+  echo "  -p2, --pipe-to <cmd>        Pipe the transcribed text to the specified command (e.g., 'wc -m')"
+  echo "  -V, --version               Show the version number"
+  echo "  -q, --quiet                 Suppress the banner and settings"
+  echo "  -h, --help                  Display this help message"
   echo "To stop the app, press Ctrl+C"
   exit 0
 }
@@ -141,6 +143,15 @@ while [[ $# -gt 0 ]]; do
         echo "Directory does not exist: $OUTPUT_DIR"
         exit 1
       fi
+      shift
+      shift
+      ;;
+    -g|--granularities)
+      if [[ ! $2 || $2 == -* ]]; then
+        echo "Error: Missing value for $1"
+        exit 1
+      fi
+      GRANULARITIES="$2"
       shift
       shift
       ;;
@@ -354,7 +365,12 @@ function convert_audio_to_text() {
     --header \"Content-Type: multipart/form-data\" \
     --form \"file=@$output_file\" \
     --form \"model=$MODEL\" \
-    --form \"response_format=json\""
+    --form \"response_format=verbose_json\""
+
+  # Add optional parameters to the curl command when GANULARITIES is not set to none
+  if [ "$GRANULARITIES" != "none" ]; then
+    curl_command+=" --form \"timestamp_granularities[]=${GRANULARITIES}\""
+  fi
 
   if [ -n "$PROMPT" ]; then
     curl_command+=" --form \"prompt=$PROMPT\""
@@ -376,7 +392,12 @@ function convert_audio_to_text() {
     maxretries=$((maxretries - 1))
   done
 
-  transcription=$(echo "$response" | jq -r '.text')
+  # if GRAINULARITIES is set to `none`, `.text` will be returned
+  if [ "$GRANULARITIES" != "none" ]; then
+    transcription=$(echo "$response")
+  else
+    transcription=$(echo "$response" | jq -r '.text')
+  fi
   
   # Check if the curl command was successful
   # retry until successful or max retries reached
@@ -407,7 +428,6 @@ function convert_audio_to_text() {
 
 # Handle the script termination: clean up and save transcriptions
 function handle_exit() {
-
   # Wait for all background jobs to finish
   wait
 
@@ -432,10 +452,16 @@ function handle_exit() {
     exit
   fi
 
-  # If output directory is specified, create a text file with the accumulated text in the specified directory
+  # If output directory is specified, create a file with the accumulated text in the specified directory
   if [ -n "$OUTPUT_DIR" ]; then
     timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
-    echo "$accumulated_text" > "$OUTPUT_DIR/transcription_$timestamp.txt"
+    # if GRAINULARITIES is set to `none`, a text file will be created
+    if [ "$GRANULARITIES" != "none" ]; then
+      echo "$accumulated_text" > "$OUTPUT_DIR/transcription_$timestamp.json"
+    # otherwise, a JSON file will be created
+    else
+      echo "$accumulated_text" > "$OUTPUT_DIR/transcription_$timestamp.txt"
+    fi
   fi
 
   # Copy the accumulated text to the clipboard
@@ -546,4 +572,3 @@ done
 
 # Handle final cleanup and exit
 handle_exit
-
