--pipe-to option added

diff --git a/whisper-stream b/whisper-stream
--- a/whisper-stream
+++ b/whisper-stream
@@ -1,17 +1,18 @@
 #!/bin/bash
 
-VERSION="1.0.6"
+VERSION="1.0.7"
 
 # Set the default sensitivity values
 MIN_VOLUME=1%
 SILENCE_LENGTH=1.5
-ONESHOOT=false
+ONESHOT=false
 DURATION=0
 TOKEN=""
 OUTPUT_DIR=""
 PROMPT=""
 LANGUAGE=""
 AUDIO_FILE=""
+PIPE_TO_CMD=""
 
 # Function to display the help message
 function display_help() {
@@ -26,6 +27,7 @@ function display_help() {
   echo "  -r, --prompt <value>     Set the prompt for the API call"
   echo "  -l, --language <value>   Set the language in ISO-639-1 format"
   echo "  -f, --file <value>       Set the audio file to be transcribed"
+  echo "  -p2, --pipe-to <cmd>     Pipe the transcribed text to the specified command (e.g., 'wc -m')"
   echo "  -V, --version            Show the version number"
   echo "  -h, --help               Display this help message"
   echo "To stop the app, press Ctrl+C"
@@ -80,45 +82,86 @@ while [[ $# -gt 0 ]]; do
   key="$1"
   case $key in
     -v|--volume)
+      if [[ ! $2 || $2 == -* ]]; then
+        echo "Error: Missing value for $1"
+        exit 1
+      fi
       MIN_VOLUME="$2"
       shift
       shift
       ;;
     -s|--silence)
+      if [[ ! $2 || $2 == -* ]]; then
+        echo "Error: Missing value for $1"
+        exit 1
+      fi
       SILENCE_LENGTH="$2"
       shift
       shift
       ;;
     -o|--oneshot)
-      ONESHOOT=true
+      ONESHOT=true
       shift
       ;;
     -d|--duration)
+      if [[ ! $2 || $2 == -* ]]; then
+        echo "Error: Missing value for $1"
+        exit 1
+      fi
       DURATION="$2"
       shift
       shift
       ;;
     -t|--token)
+      if [[ ! $2 || $2 == -* ]]; then
+        echo "Error: Missing value for $1"
+        exit 1
+      fi
       TOKEN="$2"
       shift
       shift
       ;;
     -p|--path)
+      if [[ ! $2 || $2 == -* ]]; then
+        echo "Error: Missing value for $1"
+        exit 1
+      fi
       OUTPUT_DIR="$2"
       shift
       shift
       ;;
     -r|--prompt)
+      if [[ ! $2 || $2 == -* ]]; then
+        echo "Error: Missing value for $1"
+        exit 1
+      fi
       PROMPT="$2"
       shift
       shift
       ;;
     -l|--language)
+      if [[ ! $2 || $2 == -* ]]; then
+        echo "Error: Missing value for $1"
+        exit 1
+      fi
       LANGUAGE="$2"
       shift
       shift
       ;;
+    -p2|--pipe-to)
+      if [[ ! $2 || $2 == -* ]]; then
+        echo "Error: Missing cmd for $1"
+        exit 1
+      fi
+      PIPE_TO_CMD="$2"
+      shift
+      shift
+      ;;
     -f|--file)
+      if [[ ! $2 || $2 == -* ]]; then
+        echo "Error: Missing value for $1"
+        exit 1
+      fi
       AUDIO_FILE="$2"
       check_audio_file "$AUDIO_FILE"
       shift
@@ -140,7 +183,7 @@ done
 
 # If the version option is specified, display the version number and exit
 if [ "$SHOW_VERSION" = true ]; then
-  echo "Whisper Stream Transcriber version: $VERSION"
+  echo "Whisper Stream Voice-to-Text Transcriber (version: $VERSION)"
   exit
 fi
 
@@ -180,6 +223,12 @@ function get_macos_input_device() {
   fi
 }
 
+# Function to get the volume of the audio input on macOS
+function get_macos_input_volume() {
+  local input_volume=$(osascript -e "input volume of (get volume settings)")
+  echo "$input_volume%"
+}
+
 # Function to get the name of the current audio input device on Linux
 function get_linux_input_device() {
   # if arecord command available
@@ -190,13 +239,22 @@ function get_linux_input_device() {
   fi
 }
 
+function get_linux_input_volume() {
+  # Check if amixer command is available and executable
+  if [ -x "$(command -v amixer)" ]; then
+    local input_volume=$(amixer sget Capture | grep 'Left:' | awk -F'[][]' '{ print $2 }')
+    echo "$input_volume"
+    return
+  fi
+}
+
 # Function to display current settings
 function display_settings() {
   echo ""
   echo $'\e[1;34m'Whisper Stream Transcriber$'\e[0m' ${VERSION}
-  echo $'\e[1;33m'----------------------------------------$'\e[0m'
+  echo $'\e[1;33m'---------------------------------------------$'\e[0m'
   echo "Current settings:"
-  echo "  Minimum volume: $MIN_VOLUME"
+  echo "  Volume threshold: $MIN_VOLUME"
   echo "  Silence length: $SILENCE_LENGTH seconds"
   echo "  Input language: ${LANGUAGE:-Not specified}"
 
@@ -209,8 +267,14 @@ function display_settings() {
   if [ -n "$input_device" ]; then
     echo "  Input device: $input_device"
   fi
+
+  # Get the input volume based on the operating system
+  local input_volume=$(get_input_volume)
+  if [ -n "$input_volume" ]; then
+    echo "  Input volume: $input_volume"
+  fi
   
-  echo $'\e[1;33m'----------------------------------------$'\e[0m'
+  echo $'\e[1;33m'---------------------------------------------$'\e[0m'
   echo To stop the app, press $'\e[0;36m'Ctrl+C$'\e[0m'
   echo ""
 }
@@ -223,6 +287,22 @@ function get_input_device() {
       ;;
     Linux)
       get_linux_input_device
+      ;;
+    *)
+      echo "Unknown operating system"
+      ;;
+  esac
+}
+
+
+# Function to get the volume of the current audio input device based on the operating system
+function get_input_volume() {
+  case "$(uname)" in
+    Darwin)
+      get_macos_input_volume
+      ;;
+    Linux)
+      get_linux_input_volume
       ;;
     *)
       echo "Unknown operating system"
@@ -277,8 +357,13 @@ function convert_audio_to_text() {
     return 1
   fi
 
-  echo -n -e '\r'
+  echo -ne "\r"
   echo "$transcription"
+
+  if [ -n "$PIPE_TO_CMD" ]; then
+    result=$(echo "$transcription" | $PIPE_TO_CMD)
+    echo $result
+  fi
   
   # Remove the output audio file unless the `-f` option is specified
   if [ -z "$AUDIO_FILE" ]; then
@@ -292,8 +377,8 @@ function convert_audio_to_text() {
 # Function to handle script termination
 function handle_exit() {
 
-  # Clear the line
-  echo -e '\r'
+ # Clear the current line
+  printf "\r\e[K\n"
 
   # Wait for all background jobs to finish
   wait
@@ -396,7 +481,7 @@ function custom_timeout() {
 if [ -n "$AUDIO_FILE" ]; then
   echo ""
   echo $'\e[1;34m'Whisper Stream Transcriber$'\e[0m' ${VERSION}
-  echo $'\e[1;33m'----------------------------------------$'\e[0m'
+  echo $'\e[1;33m'---------------------------------------------$'\e[0m'
   echo "Current settings:"
   echo "  Input language: ${LANGUAGE:-Not specified}"
   echo "  Input file: $AUDIO_FILE"
@@ -405,7 +490,7 @@ if [ -n "$AUDIO_FILE" ]; then
     echo "  Output Dir: $OUTPUT_DIR"
   fi
   
-  echo $'\e[1;33m'----------------------------------------$'\e[0m'
+  echo $'\e[1;33m'---------------------------------------------$'\e[0m'
   echo $'\e[0;36m'Please wait ...$'\e[0m'
   echo ""
 
@@ -474,7 +559,7 @@ $line"
     echo "No audio recorded."
   fi
 
-  if [ "$ONESHOOT" = true ]; then
+  if [ "$ONESHOT" = true ]; then
     break
   fi
 done
